# This is a basic workflow to help you get started with Actions

name: lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  NPM_CONFIG_IGNORE_SCRIPTS: 'true'
  NPM_CONFIG_BEFORE: ''
  PNPM_CONFIG_MINIMUM_RELEASE_AGE: '1440' # 1 dayhour


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set NPM_CONFIG_BEFORE
        run: |
          echo "NPM_CONFIG_BEFORE=$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: latest

      # Run scripts
      - name: Install dependencies
        run: pnpm install
      - name: linting
        run: pnpm lint
