# This is a basic workflow to help you get started with Actions

name: lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Run scripts
      - name: Install dependencies
        run: pnpm install
      - name: linting
        run: pnpm lint
